apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: server-a-deploy 
  labels:
    app: api 
sepc:
  replicas: 1
  selector:
    matchLables:
      app: server-a-api 
  template:
    metadata:
      labels:
        app: server-a-api 
    sepc:
      containers:
        - name: server-a-con 
          image: moshe5434/data_pipeline/server-a:v1 
          ports:
            - containerPort: 8000
          env:
            SERVER_B_NAME: "server-b"
            SERVER_B_PORT: "8000"
            SERVER_B_TIMEOUT: "5"
            initContainers:
        - name: wait-for-server-b
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv service-b 8000; do echo waiting for server-b...; sleep 2; done"]

    

   