apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-c-deploy
sepc:
  selector:
    matchLabels:
     app: server-c-api
  template:
    metadata:
      labels:
        app: server-c-api 
    sepc:
      containers:
        - name: server-c-con
          image: moshe5434/data_pipeline/server-c:v1
          ports:
            - port: 8000
              targetPort: 8000
          env:
            TABLE_NAME: "records_table"
            DATABASE_NAME: "db_weather"
            DATABASE_HOST: "mysql-service"
            DATABASE_USER: "root"
            DATABASE_PASSWORD: "my-pw"
            DATABASE_PORT: "3306"
        - name: wait-for-mysql
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv mysql-service 3306; do echo waiting for mysql-service...; sleep 2; done"]

    