apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: server-a-deploy 
  labels:
    app: api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-a-api 
  template:
    metadata:
      labels:
        app: server-a-api 
    spec:
      containers:
        - name: server-a-con 
          image: moshe5434/pipeline-project-server-a:v1 
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_B_NAME
              value: "service-b"
            - name: SERVER_B_PORT
              value: "8000"
            - name: SERVER_B_TIMEOUT
              value: "5"
      initContainers:
      - name: wait-for-server-b
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv service-b 8000; do echo waiting for server-b...; sleep 2; done"]

    

   