apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-c-deploy
spec:
  selector:
    matchLabels:
     app: server-c-api
  template:
    metadata:
      labels:
        app: server-c-api 
    spec:
      containers:
        - name: server-c-con
          image: moshe5434/pipeline-project-server-c:v1
          ports:
          - containerPort: 8000
          env:
            - name: TABLE_NAME
              value: "records_table"
            - name: DATABASE_NAME
              value: "db_weather"
            - name: DATABASE_HOST
              value: "mysql-service"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "my-pw"
            - name: DATABASE_PORT
              value: "3306"
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv mysql-service 3306; do echo waiting for mysql-service...; sleep 2; done"]

    