FROM python:3.11-slim

WORKDIR /app

COPY server-b/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 

COPY shared /app/shared

COPY server-b/app  ./app

EXPOSE 8000

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
